use serde::Deserialize;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Deserialize)]
struct GrammarConfig {
    language: Vec<LanguageEntry>,
}

#[derive(Deserialize)]
struct LanguageEntry {
    name: String,
    /// Rust crate identifier exporting LANGUAGE and NODE_TYPES.
    rust_crate: String,
    extensions: Vec<String>,
    queries: Option<String>,
    /// Bonsai-owned compatibility metadata layered over the released grammar.
    supertypes: Option<std::collections::BTreeMap<String, Vec<String>>>,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let config_path = manifest_dir.join("grammars.toml");
    println!("cargo:rerun-if-changed={}", config_path.display());

    let config_str = fs::read_to_string(&config_path)
        .unwrap_or_else(|e| panic!("Failed to read {}: {e}", config_path.display()));
    let config: GrammarConfig = toml::from_str(&config_str)
        .unwrap_or_else(|e| panic!("Failed to parse {}: {e}", config_path.display()));

    generate_languages_rs(&out_dir, &config.language, &manifest_dir);
}

fn validate_identifier(name: &str) -> &str {
    assert!(
        !name.is_empty() && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'),
        "invalid Rust identifier (must be [a-zA-Z0-9_]+): {name:?}"
    );
    name
}

fn escape_rust_string(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            '\\' => "\\\\".to_string(),
            '"' => "\\\"".to_string(),
            '\n' => "\\n".to_string(),
            '\r' => "\\r".to_string(),
            '\t' => "\\t".to_string(),
            '\0' => "\\0".to_string(),
            c => c.to_string(),
        })
        .collect()
}

fn embed_scm_file(dir: &Path, filename: &str) -> String {
    let path = dir.join(filename);
    if path.exists() {
        println!("cargo:rerun-if-changed={}", path.display());
        let content = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("Failed to read {}: {e}", path.display()));
        format!("Some(\"{}\")", escape_rust_string(&content))
    } else {
        "None".to_string()
    }
}

fn generate_languages_rs(out_dir: &Path, languages: &[LanguageEntry], manifest_dir: &Path) {
    let mut code = String::new();
    writeln!(code, "// Auto-generated by build.rs — do not edit").unwrap();
    writeln!(code, "use tree_sitter::Language;").unwrap();
    writeln!(code).unwrap();

    for lang in languages {
        validate_identifier(&lang.name);
        validate_identifier(&lang.rust_crate);
        for ext in &lang.extensions {
            validate_identifier(ext);
        }
    }

    writeln!(code, "pub struct LanguageInfo {{").unwrap();
    writeln!(code, "    pub name: &'static str,").unwrap();
    writeln!(code, "    pub extensions: &'static [&'static str],").unwrap();
    writeln!(code, "    pub locals_scm: Option<&'static str>,").unwrap();
    writeln!(code, "    pub tags_scm: Option<&'static str>,").unwrap();
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    writeln!(
        code,
        "pub fn get_language(name: &str) -> Option<Language> {{"
    )
    .unwrap();
    writeln!(code, "    match name {{").unwrap();
    for lang in languages {
        writeln!(
            code,
            "        \"{}\" => Some(Language::new({}::LANGUAGE)),",
            escape_rust_string(&lang.name),
            lang.rust_crate
        )
        .unwrap();
    }
    writeln!(code, "        _ => None,").unwrap();
    writeln!(code, "    }}").unwrap();
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    writeln!(
        code,
        "pub fn get_language_by_extension(ext: &str) -> Option<(&'static str, Language)> {{"
    )
    .unwrap();
    writeln!(code, "    match ext {{").unwrap();
    for lang in languages {
        let pattern = lang
            .extensions
            .iter()
            .map(|e| format!("\"{}\"", escape_rust_string(e)))
            .collect::<Vec<_>>()
            .join(" | ");
        writeln!(
            code,
            "        {pattern} => get_language(\"{}\").map(|language| (\"{}\", language)),",
            escape_rust_string(&lang.name),
            escape_rust_string(&lang.name)
        )
        .unwrap();
    }
    writeln!(code, "        _ => None,").unwrap();
    writeln!(code, "    }}").unwrap();
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    writeln!(
        code,
        "pub fn list_languages() -> &'static [LanguageInfo] {{"
    )
    .unwrap();
    writeln!(code, "    &[").unwrap();
    for lang in languages {
        let extensions = lang
            .extensions
            .iter()
            .map(|e| format!("\"{}\"", escape_rust_string(e)))
            .collect::<Vec<_>>()
            .join(", ");
        let (locals, tags) = match &lang.queries {
            Some(dir) => {
                let path = manifest_dir.join(dir);
                (
                    embed_scm_file(&path, "locals.scm"),
                    embed_scm_file(&path, "tags.scm"),
                )
            }
            None => ("None".to_string(), "None".to_string()),
        };
        writeln!(code, "        LanguageInfo {{ name: \"{}\", extensions: &[{extensions}], locals_scm: {locals}, tags_scm: {tags} }},", escape_rust_string(&lang.name)).unwrap();
    }
    writeln!(code, "    ]").unwrap();
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    writeln!(
        code,
        "/// Return the released grammar's embedded node-types.json."
    )
    .unwrap();
    writeln!(
        code,
        "pub fn get_node_types_json(name: &str) -> Option<&'static str> {{"
    )
    .unwrap();
    writeln!(code, "    match name {{").unwrap();
    for lang in languages {
        writeln!(
            code,
            "        \"{}\" => Some({}::NODE_TYPES),",
            escape_rust_string(&lang.name),
            lang.rust_crate
        )
        .unwrap();
    }
    writeln!(code, "        _ => None,").unwrap();
    writeln!(code, "    }}").unwrap();
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    writeln!(
        code,
        "/// Return Bonsai-owned compatibility augmentations for a language."
    )
    .unwrap();
    writeln!(code, "pub fn get_config_supertypes(name: &str) -> &'static [(&'static str, &'static [&'static str])] {{").unwrap();
    writeln!(code, "    match name {{").unwrap();
    for lang in languages {
        let mappings = lang
            .supertypes
            .as_ref()
            .map(|m| m.iter().collect::<Vec<_>>())
            .unwrap_or_default();
        if mappings.is_empty() {
            writeln!(
                code,
                "        \"{}\" => &[],",
                escape_rust_string(&lang.name)
            )
            .unwrap();
        } else {
            writeln!(code, "        \"{}\" => &[", escape_rust_string(&lang.name)).unwrap();
            for (supertype, subtypes) in mappings {
                let subtypes = subtypes
                    .iter()
                    .map(|s| format!("\"{}\"", escape_rust_string(s)))
                    .collect::<Vec<_>>()
                    .join(", ");
                writeln!(
                    code,
                    "            (\"{}\", &[{subtypes}]),",
                    escape_rust_string(supertype)
                )
                .unwrap();
            }
            writeln!(code, "        ],").unwrap();
        }
    }
    writeln!(code, "        _ => &[],").unwrap();
    writeln!(code, "    }}").unwrap();
    writeln!(code, "}}").unwrap();

    let output_path = out_dir.join("languages.rs");
    fs::write(&output_path, code)
        .unwrap_or_else(|e| panic!("Failed to write {}: {e}", output_path.display()));
}
