use serde::Deserialize;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Deserialize)]
struct GrammarConfig {
    language: Vec<LanguageEntry>,
}

#[derive(Deserialize)]
struct LanguageEntry {
    name: String,
    grammar: String,
    extensions: Vec<String>,
    src: String,
    supertypes: Option<String>,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let workspace_root = manifest_dir.parent().unwrap().parent().unwrap();
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let config_path = workspace_root.join("grammars.toml");
    println!("cargo:rerun-if-changed={}", config_path.display());

    let config_str = fs::read_to_string(&config_path)
        .unwrap_or_else(|e| panic!("Failed to read {}: {}", config_path.display(), e));
    let config: GrammarConfig = toml::from_str(&config_str)
        .unwrap_or_else(|e| panic!("Failed to parse {}: {}", config_path.display(), e));

    for lang in &config.language {
        compile_grammar(workspace_root, lang);
    }

    generate_languages_rs(&out_dir, &config.language);
}

fn compile_grammar(workspace_root: &Path, lang: &LanguageEntry) {
    let grammar_dir = workspace_root.join(&lang.grammar);
    let src_dir = grammar_dir.join(&lang.src);

    let parser_c = src_dir.join("parser.c");
    assert!(
        parser_c.exists(),
        "parser.c not found at {}",
        parser_c.display()
    );
    println!("cargo:rerun-if-changed={}", parser_c.display());

    let mut build = cc::Build::new();
    build
        .include(&src_dir)
        .flag_if_supported("-std=c11")
        .flag_if_supported("-Wno-unused-parameter")
        .flag_if_supported("-Wno-trigraphs")
        .file(&parser_c);

    let scanner_c = src_dir.join("scanner.c");
    if scanner_c.exists() {
        println!("cargo:rerun-if-changed={}", scanner_c.display());
        build.file(&scanner_c);
    }

    build.compile(&format!("tree_sitter_{}", lang.name));

    // Handle C++ scanner separately if present
    let scanner_cc = src_dir.join("scanner.cc");
    if scanner_cc.exists() {
        println!("cargo:rerun-if-changed={}", scanner_cc.display());
        cc::Build::new()
            .cpp(true)
            .include(&src_dir)
            .flag_if_supported("-std=c++14")
            .flag_if_supported("-Wno-unused-parameter")
            .file(&scanner_cc)
            .compile(&format!("tree_sitter_{}_scanner_cpp", lang.name));
    }
}

fn generate_languages_rs(out_dir: &Path, languages: &[LanguageEntry]) {
    let mut code = String::new();

    writeln!(code, "// Auto-generated by build.rs — do not edit").unwrap();
    writeln!(code).unwrap();
    writeln!(code, "use tree_sitter::Language;").unwrap();
    writeln!(code, "use tree_sitter_language::LanguageFn;").unwrap();
    writeln!(code).unwrap();

    // extern "C" declarations
    writeln!(code, "extern \"C\" {{").unwrap();
    for lang in languages {
        writeln!(code, "    fn tree_sitter_{}() -> *const ();", lang.name).unwrap();
    }
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    // LanguageInfo struct
    writeln!(code, "pub struct LanguageInfo {{").unwrap();
    writeln!(code, "    pub name: &'static str,").unwrap();
    writeln!(code, "    pub extensions: &'static [&'static str],").unwrap();
    writeln!(code, "    pub supertypes_scm: Option<&'static str>,").unwrap();
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    // get_language function
    writeln!(code, "pub fn get_language(name: &str) -> Option<Language> {{").unwrap();
    writeln!(code, "    match name {{").unwrap();
    for lang in languages {
        writeln!(
            code,
            "        \"{}\" => Some(Language::new(unsafe {{ LanguageFn::from_raw(tree_sitter_{}) }})),",
            lang.name, lang.name
        )
        .unwrap();
    }
    writeln!(code, "        _ => None,").unwrap();
    writeln!(code, "    }}").unwrap();
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    // get_language_by_extension function
    writeln!(
        code,
        "pub fn get_language_by_extension(ext: &str) -> Option<(&'static str, Language)> {{"
    )
    .unwrap();
    writeln!(code, "    match ext {{").unwrap();
    for lang in languages {
        let ext_pattern = lang
            .extensions
            .iter()
            .map(|e| format!("\"{}\"", e))
            .collect::<Vec<_>>()
            .join(" | ");
        writeln!(
            code,
            "        {} => get_language(\"{}\").map(|l| (\"{}\", l)),",
            ext_pattern, lang.name, lang.name
        )
        .unwrap();
    }
    writeln!(code, "        _ => None,").unwrap();
    writeln!(code, "    }}").unwrap();
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    // list_languages function
    writeln!(
        code,
        "pub fn list_languages() -> &'static [LanguageInfo] {{"
    )
    .unwrap();
    writeln!(code, "    &[").unwrap();
    for lang in languages {
        let exts = lang
            .extensions
            .iter()
            .map(|e| format!("\"{}\"", e))
            .collect::<Vec<_>>()
            .join(", ");
        let supertypes = match &lang.supertypes {
            Some(s) => format!("Some(\"{}\")", s),
            None => "None".to_string(),
        };
        writeln!(
            code,
            "        LanguageInfo {{ name: \"{}\", extensions: &[{}], supertypes_scm: {} }},",
            lang.name, exts, supertypes
        )
        .unwrap();
    }
    writeln!(code, "    ]").unwrap();
    writeln!(code, "}}").unwrap();

    let output_path = out_dir.join("languages.rs");
    fs::write(&output_path, code)
        .unwrap_or_else(|e| panic!("Failed to write {}: {}", output_path.display(), e));
}
